name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Bitwarden Secrets Manager GitHub Action
      uses: bitwarden/sm-action@f1de238fc00c738c56140796018be9084c2b5d21 # v2.1.0
      with:
        access_token: ${{ secrets.ACCESS_TOKEN }}
        secrets: |
          d8a56663-858c-4aac-b0a2-afcd00edf2f1 > DOCKER_USER
          98fc7325-57d2-4910-b37c-afcd00ed81b7 > DOCKER_PASSWORD

    - uses: actions/checkout@v2
    - name: docker login
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build
      run: docker build . --file Dockerfile --tag $DOCKER_USER/pyporwave:latest
    - name: docker push
      run: docker push $DOCKER_USER/pyporwave:latest
